name: node deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v4

      - name: login to docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOKCER_TOKEN }}

      - name: build docker image
        run: docker build -t vrajpaatel/react_app .
      
      - name: publish docker image
        run: docker push vrajpaatel/react_app:latest
  
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: pull image from the docker hub
        run: sudo docker pull vrajpaatel/react_app:latest
      
      - name: delete old container
        run : sudo docker rm -f react_app
      - name: run docker container
        run: sudo docker run -d --name react_app -p 4173:4173 vrajpaatel/react_app

    